[package]
name = "ripper"
version = "0.1.0"
authors = ["nikhil"]

[dependencies]
blake2 = "0.5"
clap = {version = "~2.19.0", features = ["yaml"]}
num_cpus = "1.5.0"
cracker = { git = "https://github.com/sgp715/Cracker.git" }
